import { EdIntel_STRIPE_LINKS } from '@/app/config/EdIntel-manifest';

export const EdIntel_TIERS = [
    {
        id: 'EdIntel-initiate',
        name: "EdIntel Initiate",
        price: 0,
        monthlyPrice: 0,
        stripeLink: EdIntel_STRIPE_LINKS.INITIATE,
        icon: "Sparkles",
        color: "zinc",
        idealFor: "Observers & New Users",
        description: "Initial access to EdIntel protocols. 14 Days.",
        features: ["Onboarding Protocol", "Basic Neural Access", "District Identity Sync", "14-Day Lead Capture"],
        popular: false,
        badge: 'FREE',
        trialDuration: '14 Days',
        robust: false,
        tokenAllocation: 500
    },
    {
        id: 'standard-pack',
        name: "Standard Pack",
        price: 9.99,
        monthlyPrice: 9.99,
        stripeLink: EdIntel_STRIPE_LINKS.STANDARD_PACK,
        icon: "Star",
        color: "violet",
        idealFor: "Individual Teachers",
        description: "Essential productivity toolkit for educators.",
        features: ["Baseline Intelligence", "Standard Node Support", "Usage Analytics", "Full 30-Day Protocol"],
        popular: false,
        badge: 'BASIC',
        trialDuration: '30 Days',
        robust: false
    },
    {
        id: 'EdIntel-pack',
        name: "EdIntel Pack",
        price: 39.99,
        monthlyPrice: 39.99,
        stripeLink: EdIntel_STRIPE_LINKS.EdIntel_PACK,
        icon: "Crown",
        color: "amber",
        idealFor: "Detailed Educators",
        description: "High-fidelity AI tools for individual growth.",
        features: ["Advanced Node Logic", "Enhanced Dataset Link", "Priority Support", "30-Day EdIntel Trial"],
        popular: false,
        badge: 'VALUE',
        trialDuration: '30 Days',
        robust: false
    },
    {
        id: 'practitioner',
        name: "Practitioner",
        price: 49.99,
        monthlyPrice: 49.99,
        stripeLink: EdIntel_STRIPE_LINKS.PRACTITIONER,
        icon: "GraduationCap",
        color: "emerald",
        idealFor: "Classroom Specialists",
        description: "Full leadership suite for the classroom.",
        features: ["Pro Architect Tools", "Multi-Node Management", "Custom Protocol Loads", "30-Day Pro Trial"],
        popular: false,
        badge: 'POPULAR',
        trialDuration: '30 Days',
        robust: false
    },
    {
        id: 'director-pack',
        name: "Director Pack",
        price: 69.99,
        monthlyPrice: 69.99,
        stripeLink: EdIntel_STRIPE_LINKS.DIRECTOR_PACK,
        icon: "Briefcase",
        color: "blue",
        idealFor: "Department Heads",
        description: "Team-wide intelligence and strategic management.",
        features: ["Leadership Oversight", "Admin Dashboard", "District-Wide Reporting", "30-Day Director Trial"],
        popular: false,
        badge: 'LEADERSHIP',
        trialDuration: '30 Days',
        robust: true,
        tokenAllocation: 20000
    },
    {
        id: 'site-command',
        name: "Site Command",
        price: 79.99,
        monthlyPrice: 79.99,
        stripeLink: EdIntel_STRIPE_LINKS.SITE_COMMAND,
        icon: "Building",
        color: "rose",
        idealFor: "Principals & Admin",
        description: "Building-wide orchestration and staff management.",
        features: ["Full Site Authority", "Max Neural Capacity", "Unlimited Usage Tokens*", "30-Day Command Trial"],
        popular: true,
        badge: 'COMMAND',
        trialDuration: '30 Days',
        robust: true, // Featured
        tokenAllocation: 999999999 // Unlimited
    }
];

export const PRICING_CONSTANTS = {
    TRIAL_DAYS_INITIATE: 14,
    TRIAL_DAYS_STANDARD: 30,
    CURRENCY: "USD",
    PROTOCOL_VERSION: "v5.4",
    ROI_COEFFICIENT: 0.22,
};
