kind: "AppStack"
apiVersion: "v1"
runConfig:
  cpu: 1
  memoryMiB: 512
env:
  - variable: NEXT_PUBLIC_FIREBASE_API_KEY
    value: "AIzaSyDTOhPhJlfUBAJjVhQjHKdXHiBLf2jl2As"
  - variable: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
    value: "studio-9997686479-ca258.firebaseapp.com"
  - variable: NEXT_PUBLIC_FIREBASE_PROJECT_ID
    value: "studio-9997686479-ca258"
