'use client';
import { Play, Video, BookOpen, UserCircle, ExternalLink } from 'lucide-react';

export default function AIMediaHub() {
  const tutorials = [
    { title: "Parent Portal Setup", engine: "HeyGen", link: "https://www.heygen.com" },
    { title: "ROI Data Literacy", engine: "Synthesia", link: "https://www.synthesia.io" },
    { title: "Tactical System Ops", engine: "D-ID", link: "https://www.d-id.com" }
  ];

  return (
    <div className="mt-16 bg-black/60 backdrop-blur-3xl rounded-[3rem] p-12 border border-white/10 shadow-2xl">
      <div className="flex flex-col md:flex-row justify-between items-start gap-8 mb-12">
        <div>
          <h2 className="text-5xl font-black text-white tracking-tighter uppercase italic">Media Studio</h2>
          <p className="text-blue-400 font-bold tracking-[0.3em] text-xs uppercase mt-2">AI Twin Content Generation | nivlawest1911</p>
        </div>
        <div className="flex gap-4">
          <button className="px-6 py-3 bg-blue-600 rounded-2xl text-[10px] font-black uppercase text-white hover:bg-blue-500 flex items-center gap-2">
            <UserCircle className="w-4 h-4" /> Create Avatar
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-10">
        {/* VIDEO PLAYER PREVIEW */}
        <div className="relative aspect-video rounded-3xl bg-zinc-900 border border-white/5 overflow-hidden flex items-center justify-center group cursor-pointer">
          <div className="absolute inset-0 bg-gradient-to-t from-black to-transparent opacity-60" />
          <Play className="w-20 h-20 text-white/20 group-hover:text-blue-500 transition-all group-hover:scale-110" />
          <div className="absolute bottom-6 left-6">
             <p className="text-white font-bold">Latest Strategy Briefing</p>
             <p className="text-white/40 text-[10px] uppercase">Generated by Gemini 1.5 Pro & HeyGen</p>
          </div>
        </div>

        {/* TUTORIAL & ENGINE LINKS */}
        <div className="space-y-4">
          <h4 className="text-[#FFD700] text-xs font-black uppercase tracking-widest mb-6">AI Tutorial Library</h4>
          {tutorials.map((t) => (
            <a href={t.link} target="_blank" key={t.title} className="flex items-center justify-between p-5 bg-white/5 rounded-2xl border border-white/5 hover:border-blue-500/50 transition-all group">
              <div className="flex items-center gap-4">
                <div className="p-3 bg-blue-500/10 rounded-xl group-hover:bg-blue-500/20">
                  <BookOpen className="w-5 h-5 text-blue-400" />
                </div>
                <div>
                  <p className="text-white font-bold text-sm">{t.title}</p>
                  <p className="text-white/40 text-[10px] uppercase">Engine: {t.engine}</p>
                </div>
              </div>
              <ExternalLink className="w-4 h-4 text-white/20" />
            </a>
          ))}
        </div>
      </div>
    </div>
  );
}
