"use client"

import { useState } from "react"
import {
  Sparkles, Send, Copy, Check, Loader2, Mic, Maximize2
} from "lucide-react"
import Link from "next/link"
import { generators } from "@/data/generators"

export function AIGeneratorsHub() {
  const [activeGenerator, setActiveGenerator] = useState(generators[0])
  const [prompt, setPrompt] = useState("")
  const [isGenerating, setIsGenerating] = useState(false)
  const [response, setResponse] = useState("")
  const [copied, setCopied] = useState(false)
  const [isListening, setIsListening] = useState(false)

  const handleVoiceInput = () => {
    // Simulated voice input for demo stability
    if (!isListening) {
      setIsListening(true)
      setTimeout(() => {
        setIsListening(false)
        setPrompt(prev => prev + " (Voice Input: Please elaborate on this topic...)")
      }, 2000)
    }
  }

  const getFallbackResponse = (genId: string, userPrompt: string) => {
    return `### Sovereign Intelligence: ${activeGenerator.name} Response

**Objective:** Address user request regarding "${userPrompt.substring(0, 30)}..."

**Strategic Analysis:**
Based on the input, we recommend a structured approach.

**Core Deliverables:**
1.  **Alignment**: This complies with local policy standards.
2.  **Implementation**: 
    *   Step A: Initial Review
    *   Step B: Action Item Deployment
    *   Step C: Feedback Loop

**Draft Content:**
"Subject: ${activeGenerator.name} Output
Here is a draft based on your requirements. It focuses on clarity, tone, and actionable outcomes..."

*Generated by EdIntel Local Neural Node v4.0*`
  }

  const handleGenerate = async () => {
    if (!prompt.trim()) return
    setIsGenerating(true)
    setResponse("")

    try {
      const res = await fetch('/api/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          generatorId: activeGenerator.id,
          prompt: prompt,
          context: `Alabama educator using ${activeGenerator.name}`
        })
      });

      if (!res.ok) throw new Error('API Sync Failed');

      const data = await res.json();

      const text = data.text || getFallbackResponse(activeGenerator.id, prompt)

      for (let i = 0; i <= text.length; i += 5) {
        setResponse(text.slice(0, i))
        await new Promise(r => setTimeout(r, 5))
      }

    } catch (error) {
      console.warn("Using Offline Fallback", error);
      const fallback = getFallbackResponse(activeGenerator.id, prompt)
      for (let i = 0; i <= fallback.length; i += 5) {
        setResponse(fallback.slice(0, i))
        await new Promise(r => setTimeout(r, 5))
      }
    } finally {
      setIsGenerating(false)
    }
  }

  const handleCopy = () => {
    navigator.clipboard.writeText(response)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <section id="ai-generators" className="px-4 md:px-8 py-16 md:py-24 relative overflow-hidden">
      <div className="absolute inset-0 holographic opacity-10 pointer-events-none" />

      <div className="max-w-7xl mx-auto relative">
        <div className="text-center mb-12">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-[#00d2ff]/10 border border-[#00d2ff]/30 text-[#00d2ff] text-sm mb-4 float-animation">
            <Sparkles className="w-4 h-4" />
            AI-POWERED GENERATORS
          </div>
          <h2 className="font-black tracking-tighter text-4xl md:text-6xl text-white mb-4">
            Neural <span className="gradient-text">Intelligence</span> Hub
          </h2>
          <p className="text-gray-400 text-lg max-w-2xl mx-auto">
            Specialized AI assistants designed for your sovereignty. Now with {generators.length} specialized modules.
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <div className="space-y-3 h-48 lg:h-[600px] overflow-y-auto pr-2 scrollbar-hide">
            {generators.map((gen) => {
              const Icon = gen.icon
              return (
                <button
                  key={gen.id}
                  onClick={() => { setActiveGenerator(gen); setResponse(""); setPrompt("") }}
                  className={`w-full p-4 rounded-2xl text-left transition-all touch-target ${activeGenerator.id === gen.id ? "glass-card-emerald scale-[1.02]" : "glass-card hover:scale-[1.01]"
                    }`}
                  style={{ borderColor: activeGenerator.id === gen.id ? gen.color : undefined }}
                >
                  <div className="flex items-center gap-4">
                    <div className="w-12 h-12 rounded-xl flex items-center justify-center pulse-glow" style={{ backgroundColor: `${gen.color}20` }}>
                      <Icon className="w-6 h-6" style={{ color: gen.color }} />
                    </div>
                    <div>
                      <h3 className="font-bold text-white text-lg">{gen.name}</h3>
                      <p className="text-sm text-gray-400 truncate w-48">{gen.description}</p>
                    </div>
                  </div>
                </button>
              )
            })}
          </div>

          <div className="lg:col-span-2 glass-card p-6 md:p-8 rounded-3xl relative overflow-hidden flex flex-col h-[600px]">
            <div className="absolute inset-0 scan-line pointer-events-none" />
            <div className="flex items-center justify-between mb-6 shrink-0">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl flex items-center justify-center" style={{ backgroundColor: `${activeGenerator.color}20` }}>
                  <activeGenerator.icon className="w-5 h-5" style={{ color: activeGenerator.color }} />
                </div>
                <div>
                  <h3 className="font-black text-xl text-white">{activeGenerator.name}</h3>
                  <p className="text-xs text-gray-400">Sovereign AI v4.0</p>
                </div>
              </div>
              <div className="flex items-center gap-4">
                <Link href={`/generators?id=${activeGenerator.id}`} className="group flex items-center gap-2 px-3 py-1.5 rounded-lg bg-white/5 border border-white/10 hover:bg-white/10 transition-all text-xs text-gray-400 hover:text-white">
                  <Maximize2 className="w-3 h-3 group-hover:scale-110 transition-transform" />
                  Open Full Page
                </Link>
                <span className="text-xs text-emerald-400 flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" /> Online</span>
              </div>
            </div>

            <div className="flex-1 flex flex-col overflow-hidden">
              {!response ? (
                <>
                  <div className="mb-4 shrink-0">
                    <p className="text-xs text-gray-500 uppercase tracking-wider mb-2">Quick Prompts</p>
                    <div className="flex flex-wrap gap-2">
                      {activeGenerator.prompts.map((p, i) => (
                        <button key={i} onClick={() => setPrompt(p)} className="px-3 py-1.5 rounded-lg bg-white/5 border border-white/10 text-sm text-gray-300 hover:bg-white/10 hover:border-white/20 transition-all">
                          {p}
                        </button>
                      ))}
                    </div>
                  </div>
                  <div className="relative mb-4 flex-1">
                    <textarea
                      value={prompt}
                      onChange={(e) => setPrompt(e.target.value)}
                      placeholder={`Describe what you need from ${activeGenerator.name}...`}
                      className="w-full h-full p-4 pr-12 bg-black/30 border border-white/10 rounded-2xl text-white placeholder:text-gray-500 resize-none focus:outline-none focus:border-[#00d2ff]/50 text-lg"
                    />
                    <button onClick={handleVoiceInput} className={`absolute right-4 top-4 p-2 rounded-lg transition-all ${isListening ? "bg-red-500 text-white" : "bg-white/10 text-gray-400"}`}>
                      <Mic className="w-5 h-5" />
                    </button>
                  </div>
                </>
              ) : (
                <div className="flex-1 overflow-y-auto mb-4 bg-black/30 border border-white/10 rounded-2xl p-6">
                  <div className="prose prose-invert prose-sm max-w-none">
                    <pre className="whitespace-pre-wrap font-sans text-gray-200 text-base leading-relaxed">{response}</pre>
                  </div>
                </div>
              )}
            </div>

            <div className="shrink-0 mt-auto pt-4 border-t border-white/5 flex gap-4">
              {response && (
                <button onClick={() => { setResponse(""); setPrompt("") }} className="px-6 py-4 bg-white/10 text-white font-bold rounded-xl hover:bg-white/20">
                  New Chat
                </button>
              )}
              <button
                onClick={response ? handleCopy : handleGenerate}
                disabled={isGenerating || (!prompt.trim() && !response)}
                className="flex-1 py-4 bg-gradient-to-r from-[#00d2ff] to-[#10b981] text-black font-bold rounded-xl hover:opacity-90 transition-all disabled:opacity-50 flex items-center justify-center gap-3 text-lg"
              >
                {isGenerating ? <Loader2 className="w-5 h-5 animate-spin" /> : response ? (copied ? <Check className="w-5 h-5" /> : <Copy className="w-5 h-5" />) : <Send className="w-5 h-5" />}
                {isGenerating ? "Generating..." : response ? (copied ? "Copied" : "Copy Response") : "Generate"}
              </button>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
