'use client';
import { useEffect, useState } from 'react';

export default function BoardReport() {
  const [stats, setStats] = useState({ total: 142, compliant: 142, hotspots: 3 });

  // Simulated data is already set in initial state, but we can keep the effect if we want to simulate loading later.
  // For now, static is fine.

  return (
    <div className="space-y-6">
      <h2 className="text-xl font-bold tracking-tight text-zinc-900 dark:text-white flex items-center gap-2">
        <span className="text-2xl">⚡</span> Quarterly Board Oversight Report (Interim)
      </h2>
      <div className="grid grid-cols-3 gap-4">
        <div className="text-center p-4 bg-zinc-50 dark:bg-zinc-950 rounded-2xl border border-zinc-100 dark:border-zinc-800">
          <p className="text-[10px] font-black uppercase tracking-widest text-zinc-500 mb-2">Total Audits</p>
          <div className="text-3xl font-black text-zinc-900 dark:text-white">{stats.total}</div>
        </div>
        <div className="text-center p-4 bg-zinc-50 dark:bg-zinc-950 rounded-2xl border border-zinc-100 dark:border-zinc-800">
          <p className="text-[10px] font-black uppercase tracking-widest text-zinc-500 mb-2">SB 101 Compliant</p>
          <div className="text-3xl font-black text-emerald-500">100%</div>
        </div>
        <div className="text-center p-4 bg-zinc-50 dark:bg-zinc-950 rounded-2xl border border-zinc-100 dark:border-zinc-800">
          <p className="text-[10px] font-black uppercase tracking-widest text-zinc-500 mb-2">Internal Flags</p>
          <div className="text-3xl font-black text-red-500">{stats.hotspots}</div>
        </div>
      </div>
      <p className="text-xs text-zinc-400 font-mono text-center">
        *Generated by EdIntel Project Alpha. Data grounded in ALSDE 2026 RAISE Act standards.
      </p>
    </div>
  );
}
