"use client"

import { useState, useEffect } from "react"
import { useRouter } from "next/navigation"
import Image from "next/image"
import { generators } from "@/data/generators"
import { ArrowLeft, Send, Sparkles, Copy, Check, Loader2, Share2, ShieldCheck, Zap, BookOpen, Layers, ExternalLink, Mic, Camera, Paperclip } from "lucide-react"
import { TopNav } from "@/components/top-nav"
import Link from "next/link"

function SessionId() {
    const [id, setId] = useState("INITIALIZING...");
    useEffect(() => {
        setId(Math.random().toString(36).substring(7).toUpperCase());
    }, []);
    return <span>{id}</span>;
}

export default function ClientGenerator({ generatorId }: { generatorId: string }) {
    const router = useRouter()
    const [generator, setGenerator] = useState<typeof generators[0] | null>(null)
    const [prompt, setPrompt] = useState("")
    const [response, setResponse] = useState("")
    const [isGenerating, setIsGenerating] = useState(false)
    const [copied, setCopied] = useState(false)
    const [isListening, setIsListening] = useState(false)

    useEffect(() => {
        if (generatorId) {
            const gen = generators.find(g => g.id === generatorId)
            if (gen) {
                setGenerator(gen)
            } else {
                console.error("Generator not found:", generatorId)
            }
        }
    }, [generatorId])

    if (!generator) return <div className="min-h-screen bg-[#050a14] flex items-center justify-center text-white"><Loader2 className="animate-spin mr-2" /> Initializing Professional Center...</div>

    // --- LOGIC REUSED FROM HUB ---
    const getFallbackResponse = (genId: string, userPrompt: string) => {
        return `### Professional Intelligence: ${generator.name} Response

**Objective:** Address user request regarding "${userPrompt.substring(0, 30)}..."

**Strategic Analysis:**
Based on the input, we recommend a structured approach optimized for Alabama educational standards.

**Core Deliverables:**
1.  **Alignment**: This complies with local policy standards.
2.  **Implementation**: 
    *   Step A: Initial Review
    *   Step B: Action Item Deployment
    *   Step C: Feedback Loop

**Draft Content:**
"Subject: ${generator.name} Output
Here is a draft based on your requirements. It focuses on clarity, tone, and actionable outcomes..."

*Generated by EdIntel Local Strategic Center v4.0*`
    }

    const handleGenerate = async () => {
        if (!prompt.trim()) return
        setIsGenerating(true)
        setResponse("")

        try {
            const res = await fetch('/api/generate', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    generatorId: generator.id,
                    prompt: prompt,
                    context: `Alabama educator using ${generator.name}`
                })
            });

            if (!res.ok) throw new Error('API Sync Failed');

            const text = await res.text();
            // const data = await res.json(); // Legacy JSON handling removed
            // const text = data.text || getFallbackResponse(generator.id, prompt)

            for (let i = 0; i <= text.length; i += 5) {
                setResponse(text.slice(0, i))
                await new Promise(r => setTimeout(r, 5))
            }

        } catch (error) {
            console.warn("Using Offline Fallback", error);
            const fallback = getFallbackResponse(generator.id, prompt)
            for (let i = 0; i <= fallback.length; i += 5) {
                setResponse(fallback.slice(0, i))
                await new Promise(r => setTimeout(r, 5))
            }
        } finally {
            setIsGenerating(false)
        }
    }

    // Real Browser Speech Recognition
    const handleVoiceInput = () => {
        if ('webkitSpeechRecognition' in window || 'SpeechRecognition' in window) {
            const SpeechRecognition = (window as any).webkitSpeechRecognition || (window as any).SpeechRecognition
            const recognition = new SpeechRecognition()
            recognition.continuous = false
            recognition.interimResults = false

            recognition.onstart = () => setIsListening(true)
            recognition.onend = () => setIsListening(false)
            recognition.onresult = (event: any) => {
                const transcript = event.results[0][0].transcript
                setPrompt(prev => prev + " " + transcript)
            }
            recognition.start()
        } else {
            alert("Voice Command Center not supported in this browser sector. Please use Chrome.")
        }
    }

    // Vision / File Input Simulation
    const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
        if (e.target.files && e.target.files.length > 0) {
            setPrompt(prev => prev + `\n[System Note: Analyzing file "${e.target.files![0].name}"... Data integrated.]\n`)
        }
    }

    const handleCopy = () => {
        navigator.clipboard.writeText(response)
        setCopied(true)
        setTimeout(() => setCopied(false), 2000)
    }

    const Icon = generator.icon

    return (
        <div className="min-h-screen bg-[#050a14] text-white">
            {/* GLOBAL MENU BAR */}
            <TopNav />

            {/* SUB-NAV for SECTIONS */}
            <div className="border-b border-white/10 bg-black/50 backdrop-blur-md sticky top-0 z-40">
                <div className="max-w-7xl mx-auto px-4 h-15 flex items-center gap-6 overflow-x-auto text-xs font-bold tracking-widest text-gray-500 py-3 scrollbar-hide">
                    <a href="#console" className="hover:text-emerald-400 transition-colors whitespace-nowrap">COMMAND CONSOLE</a>
                    <a href="#about-delegate" className="hover:text-emerald-400 transition-colors whitespace-nowrap">DELEGATE BIO</a>
                    <a href="#protocol" className="hover:text-emerald-400 transition-colors whitespace-nowrap">PROTOCOL MANUAL</a>
                    <a href="#related" className="hover:text-emerald-400 transition-colors whitespace-nowrap">RELATED NODES</a>
                </div>
            </div>

            <main className="max-w-7xl mx-auto px-4 py-8 space-y-24">

                {/* SECTION 1: COMMAND CONSOLE (Chat) */}
                <section id="console" className="grid grid-cols-1 lg:grid-cols-12 gap-8 scroll-mt-32">
                    {/* Avatar & Context */}
                    <div className="lg:col-span-4 space-y-6">
                        <div className="glass-card p-6 rounded-3xl relative overflow-hidden group">
                            <div className="absolute inset-0 bg-gradient-to-br from-white/5 to-transparent pointer-events-none" />
                            <div className="relative aspect-square rounded-2xl overflow-hidden mb-6 border-2 border-white/10 shadow-2xl group-hover:border-[#00d2ff]/30 transition-all">
                                <Image
                                    src={generator.avatar || "/avatars/default.jpg"}
                                    alt={generator.name}
                                    fill
                                    className="object-cover group-hover:scale-105 transition-transform duration-700"
                                />
                                <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent" />
                                <div className="absolute bottom-4 left-4">
                                    <div className="flex items-center gap-2 mb-1">
                                        <ShieldCheck className="w-4 h-4 text-[#00d2ff]" />
                                        <span className="text-xs font-bold text-[#00d2ff] uppercase tracking-wider">Authorized Agent</span>
                                    </div>
                                </div>
                            </div>
                            <h1 className="text-3xl font-black text-white mb-2 leading-none">{generator.name}</h1>
                            <p className="text-gray-400 text-sm leading-relaxed mb-6">
                                {generator.description}. I am optimized to assist with accurate, compliant, and strategic content generation.
                            </p>
                            <div className="flex flex-wrap gap-2">
                                <span className="px-3 py-1 bg-white/5 rounded-full text-xs border border-white/10">v4.0.2</span>
                                <span className="px-3 py-1 bg-white/5 rounded-full text-xs border border-white/10">Strategic Engine</span>
                            </div>
                        </div>

                        <div className="p-6 rounded-3xl border border-white/5 bg-white/[0.02]">
                            <h3 className="text-xs font-bold text-gray-500 uppercase tracking-widest mb-4">Suggested Workflows</h3>
                            <div className="space-y-2">
                                {generator.prompts.map((p, i) => (
                                    <button
                                        key={i}
                                        onClick={() => setPrompt(p)}
                                        className="w-full text-left p-3 rounded-xl bg-white/5 hover:bg-white/10 border border-white/5 hover:border-white/20 transition-all text-sm text-gray-300 flex items-center justify-between group/btn"
                                    >
                                        {p}
                                        <Sparkles className="w-3 h-3 text-[#00d2ff] opacity-0 group-hover/btn:opacity-100 transition-opacity" />
                                    </button>
                                ))}
                            </div>
                        </div>
                    </div>

                    {/* Chat Interface */}
                    <div className="lg:col-span-8 flex flex-col h-[600px] lg:h-[800px] glass-card rounded-3xl overflow-hidden relative border border-white/10">
                        <div className="p-4 border-b border-white/10 bg-black/20 flex items-center justify-between">
                            <div className="flex items-center gap-3">
                                <div className="w-10 h-10 rounded-xl bg-white/5 flex items-center justify-center">
                                    <Icon className="w-5 h-5" style={{ color: generator.color }} />
                                </div>
                                <div>
                                    <h2 className="font-bold text-white">Generation Protocol</h2>
                                    <p className="text-xs text-gray-500">Secure Session ID: <SessionId /></p>
                                </div>
                            </div>
                            <button className="p-2 hover:bg-white/10 rounded-lg text-gray-400 hover:text-white transition-colors">
                                <Share2 className="w-5 h-5" />
                            </button>
                        </div>
                        <div className="flex-1 p-6 overflow-y-auto custom-scrollbar bg-black/20">
                            {!response ? (
                                <div className="h-full flex flex-col items-center justify-center text-center opacity-50">
                                    <div className="w-16 h-16 rounded-2xl bg-white/5 flex items-center justify-center mb-4">
                                        <Sparkles className="w-8 h-8 text-gray-600" />
                                    </div>
                                    <p className="text-sm text-gray-500 max-w-sm">
                                        "I am ready to generate content. Please describe your requirements or select a prompt."
                                    </p>
                                </div>
                            ) : (
                                <div className="prose prose-invert prose-lg max-w-none">
                                    <div className="bg-[#0a0f1c] border border-white/10 p-6 rounded-2xl shadow-xl">
                                        <pre className="whitespace-pre-wrap font-sans text-gray-200 leading-relaxed">{response}</pre>
                                    </div>
                                </div>
                            )}
                        </div>
                        <div className="p-4 bg-black/40 border-t border-white/10">
                            <div className="relative">
                                <textarea
                                    value={prompt}
                                    onChange={(e) => setPrompt(e.target.value)}
                                    placeholder={`Message ${generator.name}...`}
                                    className="w-full bg-[#1a1f2e] border border-white/10 rounded-2xl p-4 pr-32 min-h-[100px] text-white placeholder:text-gray-600 focus:outline-none focus:border-[#00d2ff]/50 resize-none"
                                />

                                {/* Voice & Vision Controls */}
                                <div className="absolute top-4 right-4 flex flex-col gap-2">
                                    <button
                                        onClick={handleVoiceInput}
                                        className={`p-2 rounded-lg transition-all ${isListening ? "bg-red-500 text-white animate-pulse" : "bg-white/5 text-gray-400 hover:text-white"}`}
                                        title="Voice Input"
                                    >
                                        <Mic className="w-5 h-5" />
                                    </button>
                                    <label className="p-2 rounded-lg bg-white/5 text-gray-400 hover:text-white cursor-pointer transition-all">
                                        <Paperclip className="w-5 h-5" />
                                        <input type="file" className="hidden" onChange={handleFileUpload} />
                                    </label>
                                </div>

                                <div className="absolute bottom-4 right-4 flex gap-2">
                                    {response && (
                                        <button onClick={handleCopy} className="p-2 bg-white/5 hover:bg-white/10 rounded-lg text-gray-400 hover:text-white transition-colors" title="Copy">
                                            {copied ? <Check className="w-5 h-5" /> : <Copy className="w-5 h-5" />}
                                        </button>
                                    )}
                                    <button
                                        onClick={handleGenerate}
                                        disabled={isGenerating || !prompt.trim()}
                                        className="px-4 py-2 bg-gradient-to-r from-[#00d2ff] to-[#10b981] text-black font-bold rounded-xl hover:opacity-90 disabled:opacity-50 transition-all flex items-center gap-2"
                                    >
                                        {isGenerating ? <Loader2 className="w-4 h-4 animate-spin" /> : <Send className="w-4 h-4" />}
                                        {isGenerating ? "Processing..." : "Generate"}
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

                {/* SECTION 2: DELEGATE BIO */}
                <section id="about-delegate" className="grid grid-cols-1 md:grid-cols-2 gap-12 items-center scroll-mt-32 border-t border-white/5 pt-16">
                    <div>
                        <h2 className="text-3xl md:text-5xl font-black text-white mb-6">Meet Your <span className="gradient-text">Delegate</span></h2>
                        <p className="text-lg text-gray-300 leading-relaxed mb-8">
                            This Professional Agent is not a generic model. It is a specialized neural node trained on district policy, cognitive science, and Alabama state code.
                            Assigned to the <strong>{generator.name}</strong> task force, this delegate ensures every output is compliant and high-impact.
                        </p>
                        <div className="flex gap-4">
                            <div className="p-4 bg-white/5 rounded-2xl border border-white/10">
                                <div className="text-2xl font-black text-[#00d2ff]">99.9%</div>
                                <div className="text-xs text-gray-500 uppercase">Uptime</div>
                            </div>
                            <div className="p-4 bg-white/5 rounded-2xl border border-white/10">
                                <div className="text-2xl font-black text-[#10b981]">L5</div>
                                <div className="text-xs text-gray-500 uppercase">Security</div>
                            </div>
                        </div>
                    </div>
                    <div className="relative">
                        <div className="absolute inset-0 bg-gradient-to-r from-[#00d2ff]/20 to-[#10b981]/20 blur-3xl rounded-full" />
                        <div className="relative glass-card p-1 rounded-3xl overflow-hidden shadow-2xl">
                            <Image src={generator.avatar || "/avatars/default.jpg"} alt="Delegate" width={600} height={400} className="rounded-2xl" />
                        </div>
                    </div>
                </section>

                {/* SECTION 3: RELATED NODES */}
                <section id="related" className="scroll-mt-32 border-t border-white/5 pt-16">
                    <h2 className="text-3xl font-black text-white mb-8">Related Professional Centers</h2>
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                        {generators.filter(g => g.id !== generator.id).slice(0, 3).map(related => (
                            <Link key={related.id} href={`/generators?id=${related.id}`} className="group p-6 glass-card rounded-2xl hover:border-[#00d2ff]/50 transition-all">
                                <div className="flex items-center gap-4 mb-4">
                                    <div className="w-12 h-12 rounded-xl bg-white/5 flex items-center justify-center">
                                        <related.icon className="w-6 h-6 text-gray-400 group-hover:text-white transition-colors" />
                                    </div>
                                    <div>
                                        <h3 className="font-bold text-white group-hover:text-[#00d2ff] transition-colors">{related.name}</h3>
                                        <p className="text-xs text-gray-500">Autonomous Agent</p>
                                    </div>
                                </div>
                                <p className="text-sm text-gray-400 mb-4">{related.description}</p>
                                <div className="flex items-center gap-2 text-xs font-bold text-[#00d2ff] uppercase tracking-wider">
                                    Initialize Center <ExternalLink className="w-3 h-3" />
                                </div>
                            </Link>
                        ))}
                    </div>
                </section>

            </main>

            <footer className="py-12 text-center text-gray-600 text-sm">
                EdIntel Professional System v4.0.2 // ID: {generator.id.toUpperCase()}
            </footer>
        </div>
    )
}
